### ISSUE TITLE
Packages Install

### ISSUE THREAD

**Issue by ChouaibB** [microbiome/course_2022_FindingPheno#11]
Related to the [installation script](https://github.com/microbiome/course_2022_FindingPheno/blob/main/03-start.Rmd), `BiocManager` seems to be installed by `BiocManager`. It should rather be installed separately `install.packages("BiocManager")`.
![image](https://user-images.githubusercontent.com/86964562/149081916-daf702c4-7237-4011-9b9c-1c66b9311c4b.png)

Additionally, I don't see why making a function specifically just for that list of packages, and run it on the list of packages. Could the function perhaps just be broken down? (I guess the function defined would not be used again at any point?)

**Comment by TuomasBorman** [comment]
The intention was to make the installation as short and simple as possible, but at least that `BiocManager` part does not work. Moreover, I'm not sure if every CRAN package can be installed via BiocManager succesfully

**Comment by ChouaibB** [comment]
That's true, it is supposed to be simple. And eventually I was thinking the same too about installing CRAN packages separately from the Bioc ones would be safer.
The [original script](https://microbiome.github.io/course_2022_miaverse/getting-started.html#checklist-before-the-course) to me looks still simple and self explanatory (well commented and good objects naming).
If this is to be kept... perhaps breaking it down from being a function would be simpler, and commenting it making more simple.
But if it does not work for some.... then guess there is that gitter channel where we can help troubleshoot or smt?

**Comment by Begia** [comment]
Firstly, BiocManager::install() should work also for CRAN packages: [link](https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html#installing-bioconductor-cran-or-github-packages)  

I have this line at the top of my scripts:
```
if (!requireNamespace("BiocManager")) {
  install.packages("BiocManager")
}
```
This installs BiocManager if it's not installed. Then the rest of the function can run. I've usually had problems only with devtools packages and some dependencies (for some reason BiocManager::install() doesn't always fetch them even when asked to). However, these issues cannot be circumvented with other installation methods.

**Comment by TuomasBorman** [comment]
I think this version is fine since this should work

**Comment by antagomir** [comment]
Feel free to update, there is no deeper philosophy behind these choices.

**Comment by Begia** [comment]
The "BiocManager" inside the packages variable seems to be a mistake. It doesn't need to be there. The reason why I have the whole thing as a function is that it's easy to just add a package to the string (packages) without thinking if it's from CRAN or Bioconductor. This makes working on new pieces of code (which might require new packages) very easy.

In the case of this workshop, it wouldn't need to be a function, and you could just change it to this:

```
if (!requireNamespace("BiocManager")) {
  install.packages("BiocManager")
}

packages <- c("ggplot2", "ggthemes", "pheatmap", "stringr", "igraph", "ANCOMBC", "microbiome", "httpuv", "microbiomeDataSets", 
              "mia", "ecodist", "vegan", "caret", "ranger", "pdp", "MLmetrics", "precrec")

new.pkg <- packages[!(packages %in% installed.packages()[, "Package"])]
if (length(new.pkg)) {
    BiocManager::install(new.pkg, ask=T)
}
sapply(packages, require, character.only = TRUE)

```

**Comment by ChouaibB** [comment]
Yes, that's right CRAN can also be installed from Bioc. Eventually, the `BiocManager` should be separately.
I agree on making a list of packages that could take up later additions, and running the installations on them; without the need still of a function. 
Nice, that is eventually clear and simple for the audience (given a variety of experience with programming or R) as the intention was.
Ok, yes, I agree that same task can be done in multiple way, initially the issue was raised since installing `BiocManager` from `BiocManager` would not work when sent to the attendees.

**Comment by ChouaibB** [comment]
I will update this with the missing lines, thank you for the discussion.
